### ISSUE TITLE
Resaving a project does not work

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#10]
Trying to save a project after reopening it results in the following kind of exception:

java.lang.IllegalArgumentException: error double insertion: -2496257489489137213
	at com.compomics.util.db.object.ObjectsDB.insertObject(ObjectsDB.java:289)
	at com.compomics.util.experiment.identification.Identification.addObject(Identification.java:275)
	at eu.isas.peptideshaker.export.CpsExporter.saveAs(CpsExporter.java:88)
	at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:261)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$106.run(PeptideShakerGUI.java:6985)

**Comment by hbarsnes** [comment]
Hopefully fixed as part of this update: https://github.com/compomics/peptide-shaker/commit/47479567ee5b35d51dee2a734b9fc5571ead69ef
