### ISSUE TITLE
Best hit not found in the Spectrum IDs tab

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#15]
Best hit not found in the Spectrum IDs tab

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Best hit not found for spectrum qExactive01819.mgf_cus_qExactive01819.9427.9427.2 File:"qExactive01819.raw", NativeID:"controllerType=0 controllerNumber=1 scan=9427".
	at eu.isas.peptideshaker.gui.tabpanels.SpectrumIdentificationPanel.updateSpectrum(SpectrumIdentificationPanel.java:2966)
	at eu.isas.peptideshaker.gui.tabpanels.SpectrumIdentificationPanel$53.run(SpectrumIdentificationPanel.java:2773)
```

**Comment by mvaudel** [comment]
Fixed in commit 998a605049f9d7800cd3987d25452e24e8242ed8
