### ISSUE TITLE
The Default Protein Report export fails (both CLI and GUI)

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#16]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1960)
	at com.compomics.util.experiment.identification.features.IdentificationFeaturesGenerator.lambda$null$34(IdentificationFeaturesGenerator.java:1676)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.compomics.util.experiment.identification.features.IdentificationFeaturesGenerator.lambda$getConfidentModificationSites$35(IdentificationFeaturesGenerator.java:1677)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.compomics.util.experiment.identification.features.IdentificationFeaturesGenerator.getConfidentModificationSites(IdentificationFeaturesGenerator.java:1678)
	at eu.isas.peptideshaker.export.sections.PsProteinSection.getFeature(PsProteinSection.java:384)
	at eu.isas.peptideshaker.export.sections.PsProteinSection.writeSection(PsProteinSection.java:209)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:387)
	at eu.isas.peptideshaker.gui.export.FeaturesPreferencesDialog$13.run(FeaturesPreferencesDialog.java:553)
```

**Comment by CarlosHorro** [comment]
Problem in function getConfidentModificationSites occurs when it does

`sequence.substring(site - 1, site)`

when the function receives site "-1", as in modification "Acetylation of protein N-term" 
 (confidentSite:-1)

Although I suppose it will also fail with 
Pyrolidone from Q,confidentSite:0
Pyrolidone from E,confidentSite:0
Acetylation of protein N-term,confidentSite:0

and similar others.

If we receive that type of site, which would be the proper behaviour?
Example from the exception: modification "Acetylation of protein N-term" , site -1, sequence:
MDQVMQFVEPSRQFVKDSIRLVKRCTKPDRKEFQKIAMATAIGFAIMGFIGFFVKLIHIPINNIIVGG

**Comment by mvaudel** [comment]
Should be fixed in commit below.
https://github.com/compomics/compomics-utilities/commit/6817bf2611caef078f0c63fea9e7002a4e1d8475
