### ISSUE TITLE
The Default Peptide and PSM Report fails (both CLI and GUI)

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#17]
```
java.lang.NumberFormatException: For input string: "Carbamidomethylation of C"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.<init>(Integer.java:867)
	at com.compomics.util.experiment.identification.utils.PeptideUtils.lambda$getFixedModificationsAsString$12(PeptideUtils.java:179)
	at java.util.stream.Collectors.lambda$mapping$8(Collectors.java:355)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:909)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.compomics.util.experiment.identification.utils.PeptideUtils.getFixedModificationsAsString(PeptideUtils.java:177)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.getfeature(PsPeptideSection.java:349)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:193)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:375)
	at eu.isas.peptideshaker.gui.export.FeaturesPreferencesDialog$13.run(FeaturesPreferencesDialog.java:553)
```

**Comment by CarlosHorro** [comment]
Hi,

There was a problem in the algorithm managing fixed modifications which I think is solved now:

https://github.com/compomics/compomics-utilities/commit/d39f8da4f85a29a7600946cb04adf09fdae4b850
https://github.com/compomics/peptide-shaker/commit/9cee3295e2650ece6355e07be4fb6ff48f6e156a

I've checked both reports are correctly generated now.

**Comment by hbarsnes** [comment]
Great! I can confirm that both reports work on my side as well.
