### ISSUE TITLE
The Default Protein Report export fails from the command line

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#18]
```
java.lang.NullPointerException
	at eu.isas.peptideshaker.export.sections.PsProteinSection.getFeature(PsProteinSection.java:276)
	at eu.isas.peptideshaker.export.sections.PsProteinSection.writeSection(PsProteinSection.java:209)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:387)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportReport(CLIExportMethods.java:275)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:314)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)
```

Due to the ProteinDetailsProvider being null.

**Comment by hbarsnes** [comment]
Fixed
