### ISSUE TITLE
The Default Peptide Report fails from the command line

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#19]
Peptide:

```
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.utils.PeptideUtils.lambda$isDecoy$0(PeptideUtils.java:47)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.TreeMap$KeySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at com.compomics.util.experiment.identification.utils.PeptideUtils.isDecoy(PeptideUtils.java:47)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:163)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:375)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportReport(CLIExportMethods.java:275)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:314)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)
```

PSM:
```
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.utils.PeptideUtils.lambda$isDecoy$0(PeptideUtils.java:47)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.TreeMap$KeySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at com.compomics.util.experiment.identification.utils.PeptideUtils.isDecoy(PeptideUtils.java:47)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:163)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:375)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportReport(CLIExportMethods.java:275)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:314)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)
```

Due to the SequenceProvider being null.

**Comment by hbarsnes** [comment]
Fixed
