### ISSUE TITLE
The mzid export from the command line fails

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#20]
```
java.lang.NullPointerException
	at eu.isas.peptideshaker.export.MzIdentMLExport.writeSequenceCollection(MzIdentMLExport.java:567)
	at eu.isas.peptideshaker.export.MzIdentMLExport.createMzIdentMLFile(MzIdentMLExport.java:286)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportMzId(CLIExportMethods.java:339)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:355)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)
```

SequenceProvider being null.

**Comment by hbarsnes** [comment]
Fixed
