### ISSUE TITLE
The Default PSM report with non-validated matches and the Extended PSM report fails

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#22]
```
java.lang.IllegalArgumentException: No best match found for spectrum -3851710232023903969.
    at eu.isas.peptideshaker.export.sections.PsPsmSection.writeSection(PsPsmSection.java:190)
    at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:393)
    at eu.isas.peptideshaker.gui.export.FeaturesPreferencesDialog$13.run(FeaturesPreferencesDialog.java:553)
```

**Comment by mvaudel** [comment]
Fixed in commit 998a605049f9d7800cd3987d25452e24e8242ed8
