### ISSUE TITLE
Follow up analysis pepXML export fails

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#24]
```
javax.jdo.JDOUserException: Query parsing error at 'qExactive01819.mgf'  near position 17: Missing left hand side type info. Query= spectrumFile == 'qExactive01819.mgf'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.zoodb.internal.util.ReflTools.newInstance(ReflTools.java:211)
	at org.zoodb.internal.util.DBLogger.newEx(DBLogger.java:108)
	at org.zoodb.internal.util.DBLogger.newEx(DBLogger.java:99)
	at org.zoodb.internal.util.DBLogger.newUser(DBLogger.java:112)
	at org.zoodb.internal.query.QueryParserV3.tokenParsingError(QueryParserV3.java:132)
	at org.zoodb.internal.query.QueryParserV3.parseTerm(QueryParserV3.java:500)
	at org.zoodb.internal.query.QueryParserV3.parseTree(QueryParserV3.java:295)
	at org.zoodb.internal.query.QueryParserV3.parseQuery(QueryParserV3.java:247)
	at org.zoodb.jdo.impl.QueryImpl.compileQuery(QueryImpl.java:334)
	at org.zoodb.jdo.impl.QueryImpl.execute(QueryImpl.java:711)
	at com.compomics.util.db.object.ObjectsDB.getObjectsIterator(ObjectsDB.java:322)
	at com.compomics.util.experiment.identification.Identification.getIterator(Identification.java:140)
	at com.compomics.util.experiment.identification.matches_iterators.MatchesIterator.<init>(MatchesIterator.java:108)
	at com.compomics.util.experiment.identification.matches_iterators.SpectrumMatchesIterator.<init>(SpectrumMatchesIterator.java:60)
	at com.compomics.util.experiment.identification.Identification.getSpectrumMatchesIterator(Identification.java:500)
	at eu.isas.peptideshaker.followup.PepXmlExport.writeSpectrumQueries(PepXmlExport.java:453)
	at eu.isas.peptideshaker.followup.PepXmlExport.writeMsmsRunSummary(PepXmlExport.java:221)
	at eu.isas.peptideshaker.followup.PepXmlExport.writeMsmsPipelineAnalysis(PepXmlExport.java:130)
	at eu.isas.peptideshaker.followup.PepXmlExport.writePepXmlFile(PepXmlExport.java:89)
	at eu.isas.peptideshaker.gui.export.FollowupPreferencesDialog$13.run(FollowupPreferencesDialog.java:571)
```

**Comment by hbarsnes** [comment]
@dominik-kopczynski Any idea what the error message below means? And hopefully how to fix it? :)

javax.jdo.JDOUserException: Query parsing error at 'qExactive01819.mgf'  near position 17: Missing left hand side type info. Query= spectrumFile == 'qExactive01819.mgf'

**Comment by dominik-kopczynski** [comment]
== Source of the issue ==
In file: PepXmlExport.java (463): the function requires for filtering in the database the file origin of a certain spectrum, but this information is no longer available in the class SpectrumMatch.

**Comment by dominik-kopczynski** [comment]
Bug was fixed, I tested the export and it works again, at least on my test data.
