### ISSUE TITLE
Protein inference graph results in null pointer

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#30]
The creation of the peptide-level protein inference graph sometimes results in a null pointer.

Example: 

1) in the ProteinInferencePeptideLevelDialog constructor the list retainedProteins contains P08238 and Q58FF8
2) but when trying to run identification.getProteinMatch(proteinMatchKey) for the second protein key (of course then provided as a long value) this return null
3) which results in a null pointer when trying to get the corresponding peptides

So it seems like the non-leading retained proteins are not stored in the same way as the leading proteins?

Stacktrace:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.compomics.util.experiment.identification.features.IdentificationFeaturesGenerator.checkEnzymaticPeptides(IdentificationFeaturesGenerator.java:1295)
    at com.compomics.util.experiment.identification.features.IdentificationFeaturesGenerator.hasEnzymaticPeptides(IdentificationFeaturesGenerator.java:1270)
    at eu.isas.peptideshaker.gui.protein_inference.ProteinInferencePeptideLevelDialog.<init>(ProteinInferencePeptideLevelDialog.java:147)
    at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.peptideTableMouseReleased(OverviewPanel.java:2236)
```

**Comment by mvaudel** [comment]
I attempted at fixing the issue with https://github.com/compomics/peptide-shaker/commit/f7bb5f6d40b029da0fec22ae8e9d54b630cb2a91. In the new back-end, the method returns the number of termini: 
0- non-enzymatic
1- semi-enzymatic
2- enzymatic

So the table model returns an integer and not a boolean, and the gui needs to be updated accordingly.
