### ISSUE TITLE
PTM mapping can result in a null pointer

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#33]
ModificationLocalizationScorer line 1074:

`int toSelect = nToSelectMap.get(modMass);`

Example:

`nToSelectMap` only contains phospho, but `modMass` equals oxidation...

```
java.lang.NullPointerException
	at eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.getRepresentativeToSecondaryMap(ModificationLocalizationScorer.java:1074)
	at eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.getRepresentativeToSecondaryMap(ModificationLocalizationScorer.java:985)
	at eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.modificationSiteInference(ModificationLocalizationScorer.java:2666)
	at eu.isas.peptideshaker.processing.PsmProcessor.processPsm(PsmProcessor.java:164)
```

**Comment by mvaudel** [comment]
Should be fixed with https://github.com/compomics/peptide-shaker/commit/9f77478343fe1e98196f46842265a09d90bd6d14
