### ISSUE TITLE
getPossibleModificationSites fails on PTM patterns longer than one residue

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#39]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 272
	at java.lang.String.substring(String.java:1963)
	at com.compomics.util.experiment.identification.utils.ModificationUtils.getPossibleModificationSites(ModificationUtils.java:123)
	at com.compomics.util.experiment.identification.utils.ModificationUtils.getExpectedModifications(ModificationUtils.java:737)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:541)
```

Example data to reproduce the exception can be found here: http://vedlegg.uib.no/?id=800dc064d829a334ff0f94dbfb341186

**Comment by hbarsnes** [comment]
Fixed in https://github.com/compomics/compomics-utilities/commit/b7a25461a57f8d19bb3551ddc00d02742dc1e4cf
