### ISSUE TITLE
Reports crashing: possible lack of precission with long variable peptideKey?

### ISSUE THREAD

**Issue by CarlosHorro** [compomics/peptide-shaker-2.0-issue-tracker#41]
When trying to generate a "Default Peptide Report with non-validated matches" or "Default
Peptide Report" app crashes:
```

java.lang.NullPointerException
	at com.compomics.util.experiment.identification.Identification.getProteinMatches(Identification.java:461)
	at com.compomics.util.experiment.identification.features.IdentificationFeaturesGenerator.getNValidatedProteinGroups(IdentificationFeaturesGenerator.java:2591)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.getfeature(PsPeptideSection.java:402)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:193)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:375)
	at eu.isas.peptideshaker.gui.export.FeaturesPreferencesDialog$13.run(FeaturesPreferencesDialog.java:553)

```
It seems that received peptideKeys are not always valid or correspond with a PeptideMatch. Tracing them, I find things like:
```

peptideKey:-3829140918221439937
getPeptideMatch(peptideKey):com.compomics.util.experiment.identification.matches.PeptideMatch@5324cc4 oid=0.0.0.12239 state=persistent-clean
getPeptideMatch(peptideKey).getPeptide():com.compomics.util.experiment.biology.proteins.Peptide@2796baea oid=0.0.0.25492 state=persistent-clean
{P50281=[I@305586b0}

peptideKey:3912822032745665132
getPeptideMatch(peptideKey):null
```
(after this last one the app crashed)

The negative key surprisingly seems to find its PeptideMatch, but 3912822032745665132 didn't. Java's long limit is 9,223,372,036,854,775,807 , which seems really close to our values...

**Comment by hbarsnes** [comment]
I can confirm that I get the same error on the example dataset.

@mvaudel Given that this used to work before, I'd start debugging the latest changes you made to the method in question: https://github.com/compomics/compomics-utilities/commit/2110e92d42c53567a97ca08ec2fb842921b552ca?

**Comment by hbarsnes** [comment]
Bug fixed in https://github.com/compomics/peptide-shaker/commit/425ce5529b0228857c1283ee9a7ecab71c773886 and https://github.com/compomics/compomics-utilities/commit/22722c820cabbd761eabf02d0d06e387e9c844ff.

I'm not really sure why this fix works though? All I did was change the location of where the peptide key is extracted..?
