### ISSUE TITLE
DirecTag results can only be loaded on their own

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#49]
Loading DirecTag results (or PepNovo/pNovo) together with other search results, is canceled with the following exception being thrown:

```
java.lang.NullPointerException
	at eu.isas.peptideshaker.scoring.psm_scoring.PsmScorer.estimateIntermediateScores(PsmScorer.java:254)
	at eu.isas.peptideshaker.scoring.psm_scoring.PsmScorer$PsmScorerRunnable.run(PsmScorer.java:588)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Failed to import data or create the project!
java.lang.NullPointerException
	at eu.isas.peptideshaker.scoring.psm_scoring.PsmScorer.scorePsms(PsmScorer.java:443)
	at eu.isas.peptideshaker.PeptideShaker.createProject(PeptideShaker.java:291)
	at eu.isas.peptideshaker.gui.NewDialog$20.run(NewDialog.java:722)
	at java.lang.Thread.run(Thread.java:748)
```

Loading DirecTag data on it's own works fine.

**Comment by hbarsnes** [comment]
Solved with https://github.com/compomics/peptide-shaker/commit/bc83793d830d8d8ec697a88905d491ad40153856
