### ISSUE TITLE
Export to mzIdentML fails

### ISSUE THREAD

**Issue by dominik-kopczynski** [compomics/peptide-shaker-2.0-issue-tracker#9]
at eu.isas.peptideshaker.gui.export.MzIdentMLExportDialog.insertProjectData(MzIdentMLExportDialog.java:109)
	at eu.isas.peptideshaker.gui.export.MzIdentMLExportDialog.<init>(MzIdentMLExportDialog.java:74)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.exportMzIdentMLMenuItemActionPerformed(PeptideShakerGUI.java:3384)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.access$7300(PeptideShakerGUI.java:157)

**Comment by hbarsnes** [comment]
Actually, the problem was running a bit deeper, as the generated mzid file had lots of issues, like integers being treated as Unicode instead of text. But should all be fixed now. See my latest commits (both utilities and PeptideShaker) for details.
